---
title: "Fortune 500 Anti-LGBT Supporters"
author: "Rose Muiyuro"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r reading_in_the_data}
# pride_aggregates <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/pride_aggregates.csv')
fortune_aggregates <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/fortune_aggregates.csv')
# static_list <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/static_list.csv')
# pride_sponsors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/pride_sponsors.csv')
# corp_by_politicians <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/corp_by_politician.csv')
# donors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/donors.csv')
```

```{r load_packages}
library(tidyverse)
library(janitor)
library(wordcloud)
library(RColorBrewer)
library(tm)
library(wordcloud2)
library(webshot)
library(htmlwidgets)
```


```{r cleaning_data}

pride <- fortune_aggregates %>%
  select("Company", "Total Contributed") %>%
  filter(Company != "Grand Total") %>%
  clean_names()

```


Using Wordcloud

```{r word_cloud}

wordcloud(words = pride$company, freq = pride$total_contributed, 
          max.words = 100, 
          colors = brewer.pal(8, "Dark2"), 
          scale=c(3.5,0.25),
          random.order = FALSE)

png("wordcloud.png", width=12,height=8, units='in', res=300)
```

Using Wordcloud2

```{r word_cloud_2}
wordcloud2(data=pride, color='random-dark', shape = 'pentagon')

```

