---
title: "Drought in the USA"
author: "Rose Muiyuro"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r loading_packages}
library(tidyverse)
library(lubridate)
library(geofacet)
library(janitor)
library(ggthemes)
library(ggplot2)
theme_set(theme_bw())
```


```{r reading_in_the_data}
# drought <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-14/drought.csv')
drought_fips <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-14/drought-fips.csv') %>%
  mutate(decade = 10 * (year(date) %/% 10)) %>%
  clean_names()


```

```{r}
drought_fips %>%
  group_by(state, decade) %>%
  summarise(avg_dsci = mean(dsci)) %>%
  ungroup() %>%
  ggplot(data = ., 
         mapping = aes(longitude, latitude, group = "state", fill = "avg_dsci")) +
  geom_polygon() +
  facet_wrap(~decade) +
  coord_map() +
  ggthemes::theme_map() +
  scale_fill_gradient2(
    high = "red",
    low = "green",
    mid = "orange",
    midpoint = 160
  ) +
  labs(fill = "DSCI (mean)",
       title = "Average Drought Score (DSCI) per State per Decade") +
  theme(strip.text = element_text(size = 15),
        plot.title = element_text(size = 18)) 


```

