---
title: "Juneteenth"
author: "Rose Muiyuro"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r reading_in_the_data}
blackpast <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/blackpast.csv')
# census <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/census.csv')
# slave_routes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/slave_routes.csv')
# african_names <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/african_names.csv')

```


```{r loading_packages}
p_load(tidyverse, janitor, ggtext)

```

```{r data}
blckpst <- blackpast %>%
  mutate(year = as.integer(year)) %>%
  select(year:country) %>%
  filter(subject %in% c("Agricultural Development", "Black Holidays and Celebrations", "Black Women", "Slave Laws")) %>%
  filter(country == "United States") %>%
  mutate(events_new = gsub("([a-z0-9]* [a-z0-9]* [a-z0-9]* [a-z0-9]*) ", "\\1\n ", events)) %>%
    clean_names()

```


```{r}

blckpst %>%
  group_by(subject) %>%
  summarize(
        year_start = as.integer(min(year)),
        year_end = as.integer(max(year))
    ) %>%
  na.omit() %>%
  ungroup() %>%
  ggplot() +
    geom_segment(aes(x = year_start, y = fct_reorder(subject, -year_start), xend = year_end, yend = subject),
        size = 4.8, lineend = "round", color = "grey20"
    ) +
    geom_segment(aes(x = year_start, y = fct_reorder(subject, -year_start), xend = year_end, yend = subject, color = subject),
        size = 4, lineend = "round"
    ) +
    geom_text(aes(x = year_end + 6, y = subject, label = subject),
        hjust = 0, vjust = -0.2, size = 6, color = "#964B00"
    ) +
    geom_text(aes(
        x = year_end + 6, y = subject,
        label = paste0("(", year_start, "-", year_end, ")")
    ),
    hjust = 0, vjust = 1,
    size = 4.5,
    color = "#964B00"
    ) +
    ggrepel::geom_text_repel(
        data = blckpst,
        aes(x = year, y = subject, label = events_new),
        color = "grey10",
        size = 2.0,
        nudge_x = -50,
        force = 100,
        force_pull = 1,
        hjust = 0.5,
        max.overlaps = Inf,
        segment.size = 0.7,
        segment.curvature = 0.7,
        segment.angle = 70,
        segment.square = TRUE,
        segment.inflect = TRUE,
        min.segment.length = 0.5,
        box.padding = unit(0.45, "lines"),
    ) +
    geom_point(aes(x = year_start, y = subject, fill = subject),
        size = 6, shape = 22, color = "grey30"
    ) +
    scale_x_continuous(
        breaks = seq(from = 1600, to = 2100, by = 50),
        position = "top"
    ) +
    theme_minimal() +
    theme(
        legend.position = "none",
        panel.grid.major.y = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(
            size = 17
        ),
        axis.title.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()
    ) +
    expand_limits(x = c(1600, 2100)) +
    scale_fill_manual(values = c("red", "blue",
                               "green", "yellow",
                               "pink")) +
    scale_color_manual(values = c("red", "blue",
                               "green", "yellow",
                               "pink")) +
    geom_richtext(
        data = data.frame(
            x = 1900, y = 4.5,
            label = "<br>A Timeline of some events <br>
              in the History of the African-American in the USA"
        ), mapping = aes(
            x = x,
            y = y, label = label
        ), size = 5,
        inherit.aes = FALSE,
        color = "black",
        fill = "#ADD8E6",
        label.size = 0
    ) 
ggsave("juneteenth.png", plot = last_plot(), width = 18, height = 19, dpi = 300, bg = "#ffffff")
```

